### ISSUE TITLE
Error in models/network.js

### ISSUE THREAD

**Issue by sigxcpu76** [joyent/sdc-napi#2]
I didn't manage to save the logs before reinstalling, so I'll dump this from memory.

I've done a sdcadm update --all today and it looks like https://github.com/joyent/sdc-napi/commit/c98d14c66a4bb9026b128c26fcc296171975d919 made the https://github.com/joyent/sdc-napi/blob/master/lib/models/network.js to crash around like 362 with an error regarding ```subnetwork_start_ip``` not being indexed. I don't remember what was the exact job that failed with this error (provisioning a VM? a new network?)

The base for update is 20141226T032659Z. Maybe there are changes required in the database (indices created) that weren't performed by the upgrade?

**Comment by melloc** [comment]
From the sounds of it, this would have been fixed by d5b7f6ea, so I'm marking this as resolved.
